import type { NextPage } from "next";
import Head from "next/head";
import Contact from "../components/Contact";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Transformente</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1 className="font-sans font-bold h-14">Nombre Telefono</h1>
				<Contact />
			</main>
		</>
	);
};

export default Home;
